### PR TITLE
Code cleanup, string formatting, version importing

### PR DESCRIPTION
**Pull request by byarmis**
* Made it easier to bump the version-- now, just have to update the version in one place instead of two
* Changed the string formatting so people don't need to remember `\` before `'` in some strings
* Changed constant names to be more descriptive
* `main()` function now returns a string instead of directly printing, allowing other tools / functions to import and run the program without printing unless they want to
* Added backwards-compatible type-hinting

### CODE REVIEW

**Comment by diptangsu** [comment]
That is a wonderful amount of refactoring! Thanks!
I only wrote this to learn how a python package can be published to PyPi, never really thought someone else would even touch this code LOL!

However, this particular change does not look right to me. I haven't really checked it, I'll do it once I get some time.
image

Since this is a python module, we need to run it using the `-m` flag. Python's import system is pretty weird even when you properly understand it actually.

If you think it's not a mistake on your part, just let me know and I'll merge it, otherwise just make that one change and I'll merge it!

**Comment by diptangsu** [comment]
image
It is wrong. I will make the changes and fix it.

If it's a module, we can't run it as a python script; we need to run it with the `-m` flag, in which case it breaks.

**Comment by byarmis** [comment]
I apologize for that, I didn't realize that the proper way to run it was with `python -m`, not just `python`

**Comment by diptangsu** [comment]
No problem brother! It's two people now who learnt something new from this project! haha!
I didn't know this either until I wrote this code!

**Pull request merged**
